# Generated by Django 2.0 on 2018-10-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20181015_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='sign_mobile',
            new_name='signer_mobile',
        ),
        migrations.RenameField(
            model_name='orderinfo',
            old_name='sign_name',
            new_name='signer_name',
        ),
    ]
