# Generated by Django 2.0 on 2018-10-15 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20181015_2254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderinfo',
            old_name='signer_mobile',
            new_name='singer_mobile',
        ),
    ]
